### ISSUE TITLE
JA3 Issue

### ISSUE THREAD

**Issue by KawaCode** [89z/format#3] opened 2022-05-29 23:28 UTC
i dont know the issue but the error is in extension number 34.

JA3 used: 771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-16-5-34-51-43-13-45-28-41,29-23-24-25-256-257,0

**Comment by 89z** [comment] 2022-05-29 23:40
Sorry, cannot reproduce:

~~~go
package main

import (
   "github.com/89z/format/crypto"
   "net/http"
)

const ja3 = "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-16-5-34-51-43-13-45-28-41,29-23-24-25-256-257,0"

func main() {
   req, err := http.NewRequest("HEAD", "https://example.com", nil)
   if err != nil {
      panic(err)
   }
   hello, err := crypto.ParseJA3(ja3)
   if err != nil {
      panic(err)
   }
   res, err := crypto.Transport(hello).RoundTrip(req)
   if err != nil {
      panic(err)
   }
   println(res.Status) // 200 OK
}
~~~

**Comment by KawaCode** [comment] 2022-05-30 00:20
Frame 11: 320 bytes on wire (2560 bits), 320 bytes captured (2560 bits) on interface wlan0, id 0
    Interface id: 0 (wlan0)
        Interface name: wlan0
    Encapsulation type: Ethernet (1)
    Arrival Time: May 30, 2022 02:18:12.218722562 CEST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1653869892.218722562 seconds
    [Time delta from previous captured frame: 0.000291308 seconds]
    [Time delta from previous displayed frame: 0.000291308 seconds]
    [Time since reference or first frame: 0.819580673 seconds]
    Frame Number: 11
    Frame Length: 320 bytes (2560 bits)
    Capture Length: 320 bytes (2560 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ipv6:tcp:tls]
    [Coloring Rule Name: TCP]
    [Coloring Rule String: tcp]
Ethernet II, Src: CyberTAN_55:76:83 (28:39:26:55:76:83), Dst: AskeyCom_0d:c7:48 (c8:b4:22:0d:c7:48)
    Destination: AskeyCom_0d:c7:48 (c8:b4:22:0d:c7:48)
        Address: AskeyCom_0d:c7:48 (c8:b4:22:0d:c7:48)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: CyberTAN_55:76:83 (28:39:26:55:76:83)
        Address: CyberTAN_55:76:83 (28:39:26:55:76:83)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv6 (0x86dd)
Internet Protocol Version 6, Src: 2a02:3033:41e:707c:4d8c:75ad:4650:ac48, Dst: 2606:2800:220:1:248:1893:25c8:1946
    0110 .... = Version: 6
    .... 0000 0000 .... .... .... .... .... = Traffic Class: 0x00 (DSCP: CS0, ECN: Not-ECT)
        .... 0000 00.. .... .... .... .... .... = Differentiated Services Codepoint: Default (0)
        .... .... ..00 .... .... .... .... .... = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    .... 0101 0011 0100 0001 0111 = Flow Label: 0x53417
    Payload Length: 266
    Next Header: TCP (6)
    Hop Limit: 64
    Source Address: 2a02:3033:41e:707c:4d8c:75ad:4650:ac48
    Destination Address: 2606:2800:220:1:248:1893:25c8:1946
Transmission Control Protocol, Src Port: 56496, Dst Port: 443, Seq: 1, Ack: 1, Len: 234
    Source Port: 56496
    Destination Port: 443
    [Stream index: 0]
    [Conversation completeness: Complete, WITH_DATA (31)]
    [TCP Segment Len: 234]
    Sequence Number: 1    (relative sequence number)
    Sequence Number (raw): 1410204568
    [Next Sequence Number: 235    (relative sequence number)]
    Acknowledgment Number: 1    (relative ack number)
    Acknowledgment number (raw): 3185974305
    1000 .... = Header Length: 32 bytes (8)
    Flags: 0x018 (PSH, ACK)
        000. .... .... = Reserved: Not set
        ...0 .... .... = Nonce: Not set
        .... 0... .... = Congestion Window Reduced (CWR): Not set
        .... .0.. .... = ECN-Echo: Not set
        .... ..0. .... = Urgent: Not set
        .... ...1 .... = Acknowledgment: Set
        .... .... 1... = Push: Set
        .... .... .0.. = Reset: Not set
        .... .... ..0. = Syn: Not set
        .... .... ...0 = Fin: Not set
        [TCP Flags: ·······AP···]
    Window: 507
    [Calculated window size: 64896]
    [Window size scaling factor: 128]
    Checksum: 0xfb66 [unverified]
    [Checksum Status: Unverified]
    Urgent Pointer: 0
    Options: (12 bytes), No-Operation (NOP), No-Operation (NOP), Timestamps
        TCP Option - No-Operation (NOP)
            Kind: No-Operation (1)
        TCP Option - No-Operation (NOP)
            Kind: No-Operation (1)
        TCP Option - Timestamps: TSval 3657695490, TSecr 660947993
            Kind: Time Stamp Option (8)
            Length: 10
            Timestamp value: 3657695490
            Timestamp echo reply: 660947993
    [Timestamps]
        [Time since first frame in this TCP stream: 0.204412774 seconds]
        [Time since previous frame in this TCP stream: 0.000291308 seconds]
    [SEQ/ACK analysis]
        [iRTT: 0.204121466 seconds]
        [Bytes in flight: 234]
        [Bytes sent since last PSH flag: 234]
    TCP payload (234 bytes)
Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 229
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 225
            Version: TLS 1.2 (0x0303)
            Random: 62a13111128d49a05a5a5884164a499727228abff7eaddf1f082888845b4b012
                GMT Unix Time: Jun  9, 2022 01:30:25.000000000 CEST
                Random Bytes: 128d49a05a5a5884164a499727228abff7eaddf1f082888845b4b012
            Session ID Length: 32
            Session ID: 4375d98b8e5affc6c83189577a29fe9082ba003684d09a78f57f54ec5c73cc50
            Cipher Suites Length: 36
            Cipher Suites (18 suites)
                Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
                Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
                Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
                Cipher Suite: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
                Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
                Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
            Compression Methods Length: 1
            Compression Methods (1 method)
                Compression Method: null (0)
            Extensions Length: 116
            Extension: server_name (len=16)
                Type: server_name (0)
                Length: 16
                Server Name Indication extension
                    Server Name list length: 14
                    Server Name Type: host_name (0)
                    Server Name length: 11
                    Server Name: example.com
            Extension: extended_master_secret (len=0)
                Type: extended_master_secret (23)
                Length: 0
            Extension: renegotiation_info (len=1)
                Type: renegotiation_info (65281)
                Length: 1
                Renegotiation Info extension
                    Renegotiation info extension length: 0
            Extension: supported_groups (len=14)
                Type: supported_groups (10)
                Length: 14
                Supported Groups List Length: 12
                Supported Groups (6 groups)
                    Supported Group: x25519 (0x001d)
                    Supported Group: secp256r1 (0x0017)
                    Supported Group: secp384r1 (0x0018)
                    Supported Group: secp521r1 (0x0019)
                    Supported Group: ffdhe2048 (0x0100)
                    Supported Group: ffdhe3072 (0x0101)
            Extension: ec_point_formats (len=2)
                Type: ec_point_formats (11)
                Length: 2
                EC point formats Length: 1
                Elliptic curves point formats (1)
                    EC point format: uncompressed (0)
            Extension: application_layer_protocol_negotiation (len=11)
                Type: application_layer_protocol_negotiation (16)
                Length: 11
                ALPN Extension Length: 9
                ALPN Protocol
                    ALPN string length: 8
                    ALPN Next Protocol: http/1.1
            Extension: status_request (len=5)
                Type: status_request (5)
                Length: 5
                Certificate Status Type: OCSP (1)
                Responder ID list Length: 0
                Request Extensions Length: 0
            Extension: delegated_credentials (len=0)
                Type: delegated_credentials (34)
                Length: 0
                No more room for vector of length 2
                    [Expert Info (Error/Malformed): No more room for vector of length 2]
                        [No more room for vector of length 2]
                        [Severity level: Error]
                        [Group: Malformed]
            Extension: key_share (len=0)
                Type: key_share (51)
                Length: 0
            Extension: supported_versions (len=3)
                Type: supported_versions (43)
                Length: 3
                Supported Versions length: 2
                Supported Version: TLS 1.2 (0x0303)
            Extension: signature_algorithms (len=6)
                Type: signature_algorithms (13)
                Length: 6
                Signature Hash Algorithms Length: 4
                Signature Hash Algorithms (2 algorithms)
                    Signature Algorithm: ecdsa_secp256r1_sha256 (0x0403)
                        Signature Hash Algorithm Hash: SHA256 (4)
                        Signature Hash Algorithm Signature: ECDSA (3)
                    Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
                        Signature Hash Algorithm Hash: SHA256 (4)
                        Signature Hash Algorithm Signature: RSA (1)
            Extension: psk_key_exchange_modes (len=2)
                Type: psk_key_exchange_modes (45)
                Length: 2
                PSK Key Exchange Modes Length: 1
                PSK Key Exchange Mode: PSK with (EC)DHE key establishment (psk_dhe_ke) (1)
            Extension: record_size_limit (len=0)
                Type: record_size_limit (28)
                Length: 0
                Record Size Limit: 41
                Dissector processed too much data (2 bytes)
                    [Expert Info (Error/Malformed): Dissector processed too much data (2 bytes)]
                        [Dissector processed too much data (2 bytes)]
                        [Severity level: Error]
                        [Group: Malformed]
            Extension: pre_shared_key (len=0)
                Type: pre_shared_key (41)
                Length: 0
                Pre-Shared Key extension
                    No more room for vector of length 2
                        [Expert Info (Error/Malformed): No more room for vector of length 2]
                            [No more room for vector of length 2]
                            [Severity level: Error]
                            [Group: Malformed]
            [JA3 Fullstring: 771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-16-5-34-51-43-13-45-28-41,29-23-24-25-256-257,0]
            [JA3: 1af5d1fe5c1c9bdba4ec723ac5cab44f]

**Comment by KawaCode** [comment] 2022-05-30 00:20
this is the wireshark packet, check the malformed: [Severity level: Error]

**Comment by 89z** [comment] 2022-05-30 00:22
Sorry, but I am not here to provide free tech support. Closing for now. If you wish to enter into a paid contract, I can reopen, thanks.

**Comment by KawaCode** [comment] 2022-05-30 00:23
Do you have telegram?

**Closed by 89z** 2022-05-30 00:22 UTC

**Comment by 89z** [comment] 2022-05-30 00:26
You can use the email in my bio, or Discord 89z#4149

**Comment by KawaCode** [comment] 2022-05-30 00:27
I sent you friendship on Discord.
